apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    io.shyrka: ""
    io.shyrka.erebus/hypnos: "v1alpha3"
    app: shyrka-erebus
  name: erebus.shyrkaio.github.io
spec:
  group: shyrkaio.github.io
  names:
    kind: Erebus
    listKind: ErebusList
    plural: erebux
    singular: erebus
  scope: Cluster
  versions:
    - name: v1alpha3
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          #https://swagger.io/docs/specification/data-models/data-types/
          type: object
          properties:
            spec:
              type: object
              properties:
                hypnos:
                  type: boolean
                  nullable: false
                  default: false
