
apiVersion: shyrkaio.github.io/v1alpha1
kind: Hypnos
metadata:
  name: test-002
  labels:
    io.shyrka.erebus/hypnos: "sample020"
    io.shyrka.erebus/role: "test"
spec:
  namespaceTargetedLabel: "io.shyrka.erebus/hypnos=sample020"
  targetedLabel: "io.shyrka.erebus/hypnos=sample"
  resourceType:
    - "Deployment"
    - "StatefulSet"
  # this is for testing regular cron should be
  wakeup-cron: "0/5 * * * *"
  sleep-cron: "0/2 * * * *"
