apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: erebus
  labels:
    io.shyrka: ""
    io.shyrka.erebus/hypnos: "v1alpha1"
    app: shyrka-erebus
roleRef:
  name: erebus
subjects:
  - kind: ServiceAccount
    name: shyrka-erebus
    namespace: shyrka-erebus-operators
userNames:
  - system:serviceaccount:shyrka-erebus-operators:shyrka-erebus