apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: erebus
  labels:
    io.shyrka: ""
    io.shyrka.erebus/hypnos: "v1alpha1"
    app: shyrka-erebus
rules:
  - apiGroups: [""]
    resources: ["namespace"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["deployments"]
    verbs: ["list", "update"]
  - apiGroups: [""]
    resources: ["statefullset"]
    verbs: ["list", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["shyrkaio.github.io"]
    resources: ["hypnox"]
    verbs: ["watch","list", "update"]