apiVersion: apps/v1
kind: Deployment
metadata:
  name: erebus-operators
  labels:
    io.shyrka: ""
    io.shyrka.erebus/hypnos: "v1alpha2"
    app: shyrka-erebus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.shyrka: ""
        io.shyrka.erebus/hypnos: "v1alpha2"
    spec:
      serviceAccount: shyrka-erebus