apiVersion: v1
kind: Service
metadata:
  name: erebus-operators
  labels:
    io.shyrka: ""
    io.shyrka.erebus/hypnos: "v1alpha1"
    app: shyrka-erebus
  annotations:
    api.service.kubernetes.io/path: /
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: erebus-operator
  sessionAffinity: None
  type: ClusterIP